name: Release

on:
  push:
    branches: master

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set version in Env
      shell: bash
      run: |
        echo ::set-env name=package_version::`awk -F ':' '/version/ {print $2}' package.json | sed 's/\"//g' | sed 's/,//g' | sed 's/ //g'`
        echo "Version is `awk -F ':' '/version/ {print $2}' package.json | sed 's/\"//g' | sed 's/,//g' | sed 's/ //g'`"
    - uses: actions/github-script@v2.0.1
      name: Check if current version is a published release (by release tag)
      id: check_release
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        # debug: true
        script: |
          const releases = await github.repos.listReleases({
            owner: ${{github.repository_owner}},
            repo: ${{github.repository}}
          })
          // console.log(releases)
          const published_release_tags = releases.data.filter(release => !release.draft).map(release => release.tag_name)
          // console.log(published_release_tags)
          // github.event_name: ${{ github.event_name }}
          // github.ref: ${{ github.ref }}
          const isPushToMaster = ${{ startsWith(github.event_name, 'push') && github.ref == 'refs/heads/master' }}
          console.log('Is push to mster: ' + isPushToMaster)
          const newRelease = !published_release_tags.includes('v${{ env.package_version }}') && isPushToMaster
          console.log('newRelease: ' + newRelease)
          return newRelease
    outputs:
      isRelease: ${{steps.check_release.outputs.result}}
      packageVersion: ${{ env.package_version }}
  
  
  release:
    needs: [version]
    if: ${{ needs.version.outputs.isRelease }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: v${{ needs.version.outputs.packageVersion }}
        release_name: Release ${{ needs.version.outputs.packageVersion }}
        draft: false
        prerelease: false

  publish-npm:
    needs: [version]
    if: ${{ needs.version.outputs.isRelease }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-gpr:
    needs: [version]
    if: ${{ needs.version.outputs.isRelease }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: yarn config set registry https://npm.pkg.github.com/
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
