name: Send a Tweet
on: [push]
jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'TWEET=testing in production ${{github.repository}}' >> $GITHUB_ENV
      - uses: ethomson/send-tweet-action@v1
        with:
          status: "New version of ${{github.repository}}\nVersion: 1.2.3\n@github #npm"
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
